name: tickup
description: Tickup app frontend
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  dio: ^5.4.0
  supabase_flutter: ^2.2.0
  go_router: ^13.0.0
  flutter_hooks: ^0.20.5
  flame: ^1.32.0
  uuid: ^4.0.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.7
  flame_tiled: ^3.0.7
  flame_audio: ^2.11.10
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/tiles/
    - assets/images/Background/
    - assets/images/Terrain/
    - assets/images/HUD/
    - assets/images/Traps/Saw/
    - assets/images/Traps/Trampoline/
    - assets/images/Traps/Spiked Ball/
    - assets/images/Traps/Fan/
    - assets/images/Traps/Fire/
    - assets/images/Traps/Falling Platforms/
    - assets/images/Traps/Arrow/
    - assets/images/Traps/Rock Head/
    - assets/images/Traps/Spike Head/
    - assets/images/Traps/Spikes/
    - assets/images/Traps/Platforms/
    - assets/images/Traps/Blocks/
    - assets/images/Traps/Sand Mud Ice/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Items/Fruits/
    - assets/images/Main Characters/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/Enemies/Chicken/
    - assets/images/Enemies/AngryPig/
    - assets/images/Enemies/Bunny/
    - assets/images/Enemies/Chameleon/
    - assets/images/Enemies/Duck/
    - assets/images/Enemies/FatBird/
    - assets/images/Enemies/AngryPig/
    - assets/images/Enemies/AngryPig/
    - assets/images/Enemies/AngryPig/
    - assets/images/Enemies/AngryPig/
    - assets/images/HUD/
    
